default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Android build App (local build + artifacts)"
  lane :build do
    gradle(task: "assembleRelease")

    sh("mkdir -p ../build_artifacts")
    sh("cp app/build/outputs/apk/release/app-release.apk ../build_artifacts/ || true")
    sh("cp app/build/outputs/bundle/release/app-release.aab ../build_artifacts/ || true")
  end

  desc "Submit a new Beta Build (with artifacts)"
  lane :beta do
    gradle(task: "assembleRelease")

    sh("mkdir -p ../build_artifacts")
    sh("cp app/build/outputs/apk/release/app-release.apk ../build_artifacts/ || true")
    sh("cp app/build/outputs/bundle/release/app-release.aab ../build_artifacts/ || true")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
