
name: React Native CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      # # iOS Build with Fastlane
      # - name: iOS Build
      #   run: |
      #     cd ios
      #     bundle install
      #     bundle exec fastlane beta   # replace 'beta' with your iOS lane

      # Android Build with Fastlane
      - name: Android Build
        run: |
          cd android
          bundle install
          bundle exec fastlane beta   # replace 'beta' with your Android lane
